### ISSUE TITLE
App not working in side Samsung Knox

### ISSUE THREAD

**Issue by arkadym** [horizontalsystems/unstoppable-wallet-android#5728]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/4163 - there is issue i reported earlier. Few days ago installed Unstoppable into Knox folder on my Galaxy S20. And today get below screen. Neither buttons not work - keep show same screen (Back, Close, OK).
![Screenshot_20230111_102237_Unstoppable](https://user-images.githubusercontent.com/7422012/211742924-fa0ed7e1-15d5-4b6c-b450-ce9df7a397ea.jpg)

**Comment by abdrasulov** [comment]
There was an issue #5515. It may be related. It has been fixed in v 0.29. Can you please share the version of app in your device?

**Comment by arkadym** [comment]
Not sure is it related or not, at moment of try it was 0.29. Exactly because i've seen my previous reported issue closed so decided to try and found issue still there.

**Comment by abdrasulov** [comment]
App log might help us to investigate. But since the app is not opening. it's not possible to get it.

I tried several scenarios to reproduce the issue. But could not. I even reset the device pin, knox folder pin. The app works fine.

Is it the fresh install?

**Comment by arkadym** [comment]
App log, let me try collect it.
Yes, it is fresh install. Let me do another round. Today enabled log for knox folder, it is not possible get logs from knox app like any normal app, with adb logcat. Reset app once again, configured FP protection, lets wait couple days, until it get issue again. Then i'll try to collect logs.

**Comment by abdrasulov** [comment]
Thanks @arkadym

**Comment by arkadym** [comment]
Finally able to get logcat, see it attached. Did usual steps: clear data, setup FP protection in app, add one address in view mode, wait ~24 hrs.
[s20-2023-01-31-10-11.log](https://github.com/horizontalsystems/unstoppable-wallet-android/files/10543951/s20-2023-01-31-10-11.log)

**Comment by arkadym** [comment]
@abdrasulov just wondering, are the logs gave more light on possible cause of the issue ?

**Comment by abdrasulov** [comment]
@arkadym unfortunately, I didn't find possible issue causes in the logs. We installed it on other Samsung devices Knox folder. We'll keep an eye on it

**Comment by arkadym** [comment]
@abdrasulov Because I easily can recreate issue, just need to wait 1 day, is it worth may be create test build with more logging ?

**Comment by abdrasulov** [comment]
That's a good idea. Let's check it with a current development version. It is debuggable, so the log should be viewable by logcat. Github doesn't allow attaching files bigger than 25 MB. Please share your email address or write us to support.unstoppable@protonmail.com. We'll send the apk via email.

**Comment by abdrasulov** [comment]
@arkadym, could you reproduce the issue with the dev version?

**Comment by arkadym** [comment]
@abdrasulov just downloaded it, have to wait at least 1 days. Will update you.

**Comment by abdrasulov** [comment]
Please, check your email

**Comment by arkadym** [comment]
@abdrasulov finally was able to install app and setup it as usual. Anything special I have to do in addition to my normal operations ?

**Comment by abdrasulov** [comment]
Good to hear. This version has dev logs enabled. You can see them via adb. As far as I know, you are familiar with it :). Let's see if the issue can be reproduced. And if it occurs please check the dev logs and share them.

**Comment by arkadym** [comment]
Fresh log
1) s20-2023-02-15-21-01.zip - that is when I run Unstoppable first time today (last time it was > 24hrs ago) - got issue
2) s20-2023-02-15-21-17.zip - then to confirm issue cannot be resolve by simple clean data of the app. See also attached video. App force stopped, did clear data 2 times (just in case). Then click Open and it keep show same error.

[s20-2023-02-15-21-17.zip](https://github.com/horizontalsystems/unstoppable-wallet-android/files/10746175/s20-2023-02-15-21-17.zip)
[s20-2023-02-15-21-01.zip](https://github.com/horizontalsystems/unstoppable-wallet-android/files/10746176/s20-2023-02-15-21-01.zip)
[video_2023-02-15_21-22-04.mp4](https://user-images.githubusercontent.com/7422012/219118865-f67cfd85-8e85-4c2f-a73e-45db5717c747.mp4)

**Comment by abdrasulov** [comment]
@arkadym Thanks for logs. We will check it soon.

**Comment by arkadym** [comment]
@abdrasulov did logs add any light on possible cause ?

**Comment by abdrasulov** [comment]
Hi  @arkadym. Sorry for the delay.

The logs show an issue with retrieving keys from the Keystore.

```
02-15 21:18:19.785   724  2559 E keystore2: keystore2::error: Rc(ResponseCode(7)), "In get_key_entry, while trying to load key info. 15010518, Some(\"MASTER_KEY\")"
```

The app uses the key from the Android OS for data encrypting and decrypting. For some reason, the app cannot retrieve the key inside the Knox folder on your device. Unfortunately, there is no solution that we could apply in the app to fix it. We tested it on several Samsung devices. The app works fine in all of them.

**Comment by arkadym** [comment]
Sorry, i dont want to blame you :(. But issue is still there. I did tried 3 more samsung phones: s23+, s21, s10 - all have same issue. After you closed issue i started thought may be there is really something i did wrong, or may be because i never did reset, e.g. s20 is already about 3 years i'm using w/o reset, just installing official updates. fold 3 - is about 1,5 year (bought it at start). Then i realized my wife is also using samsung phones. But she never used knox (no need).
S23+ one - i bought to her last month, it is in use about 2 weeks, so i did clean setup of knox, nothing in side, copy there same test build APK i tried in s20. 
Her previous one - S21 - also never used knox folder (Secure Folder). Did clean setup of knox - after 1,5 day got issue.
Her pre-previous one S10 - same.
All the phones here are never been rooted or so, all are the very stock and always stay on latest updates...
Got idea could be processor specific issue because Fold 3 is Snapdragon, S10, S20, S23 - also. But S21 is Exynos and still has same issue.

See, i understand you may dont have idea how to fix it. Could you may be point to line of code where error happens. It's so annoying me, i almost ready try to fix it myself :). So i will try build it on my side and run may be under debug or so. I have friends who are experienced in Android dev bit more than me, will try ask them to help. Appreciate any help, is there any special to setup dev env ? Few years didnt do any Android dev already. 
Android Studio + SDK is enough ? NDK dont need ? Kotlin is ok for me.

**Comment by arkadym** [comment]
@abdrasulov Is it right place to start - https://github.com/horizontalsystems/unstoppable-wallet-android/blob/0f86fd49af97fa62252444c5424aac1f1b4aeafa/core/src/main/java/io/horizontalsystems/core/security/KeyStoreManager.kt#L44 ?

**Comment by junzhli** [comment]
hello @arkadym 
i was in trouble with the same issue before. and i end up with running my custom build on my own version in knox folder. you may try this if you are using biometric authentication.

Try setting the following
https://github.com/horizontalsystems/unstoppable-wallet-android/blob/0f86fd49af97fa62252444c5424aac1f1b4aeafa/app/src/main/java/io/horizontalsystems/bankwallet/modules/keystore/KeyStoreActivity.kt#L64
change from ```promptInfo.setAllowedAuthenticators(DEVICE_CREDENTIAL)``` to ```promptInfo.setAllowedAuthenticators(BIOMETRIC_STRONG)```  

https://github.com/horizontalsystems/unstoppable-wallet-android/blob/0f86fd49af97fa62252444c5424aac1f1b4aeafa/core/src/main/java/io/horizontalsystems/core/security/KeyStoreManager.kt#L104
chagne from ```KeyProperties.AUTH_DEVICE_CREDENTIAL or KeyProperties.AUTH_BIOMETRIC_STRONG``` to ```KeyProperties.AUTH_BIOMETRIC_STRONG```   

I was troubled with running the official build in knox folder until I build on my own. It just works perfectly on my s10+ with android 12. Notice that keystore will get invalidated if you alter biometric related authentication on security setting.

**Comment by abdrasulov** [comment]
Hi guys!

Thanks for the update. For some reason, I didn't notice your last replies.

As for the issue, that is strange. We tested it on Samsung devices like the s21+, note 10. But could not reproduce. These installs work fine.

@arkadym please let us know if the solution of @junzhli worked

I'll reopen this ticket. Let's check it once more in the next sprint.

**Comment by arkadym** [comment]
@abdrasulov Did you round of testing, so far looks like no issue. Give me time till the end of this week. Because it need to wait at least 2 times by 24-30 hours. At the moment i tested S20 only - installed app last Sat evening, Sun evening (~25 hours) got no issue. Today morning (30+ hours) - still no issue. Going to install couple more devices and spend another 3 days to test. Will update here once i finish.

**Comment by arkadym** [comment]
@abdrasulov I finished testing, it works for me! As planned did testing with 2 more phones for 2 rounds, today morning after another ~30 hours still has no issue.
